### ISSUE TITLE
Cyberpatriot rules

### ISSUE THREAD

**Issue by Reginald-Gillespie** [xFaraday/EzScript#1]
You should probably note to users that according to the cyberpatriot rules 3012.4.4.b, these scripts may not be used by any team other than yours during competitions.

And you should not that according to 3012.4.5, publicizing these scripts intended for the Cyberpatriot competition is prohibited. You should set this repository to private, as I believe it is grounds for disqualification.

**Comment by xFaraday** [comment]
If you star this repository and send proof of it in this issue I'll follow through with your request.  Otherwise begone and leave me alone lmfao im 22 years old

**Comment by Reginald-Gillespie** [comment]
And living in your mom's basement I'm sure. Google the rules yourself.

**Comment by xFaraday** [comment]
Lol damn the pride from someone with no stars 😭
